name: InvestmentOttawa
favicon: null
layout_spectrum: 0.3450209912844002
typography_spectrum: 0.7613921901211143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8314325993414968
  lightness: 0.7282606863882393
  saturation: 0.6884775711223483
  rhythmicContrast: 0.4327828297391534
purpose: []
